### PR TITLE
test: initial test setup and a couple of tests

### PR DESCRIPTION
**Pull request by ddebrunner**

### CODE REVIEW

**Review by Cerchie — COMMENTED** [review]
Testing liftoff! ✈️
Couple suggestions to add.
- For me, to get this to work, I needed to use [this package](https://www.npmjs.com/package/env-cmd) and change the package.json test command to ""test": "env-cmd mocha **/tests/*Test.js"

- The README is clear, I think it should be moved to a Testing section in the main README. 

- We need a `.gitignore` with `*.env`.
- We also need a `env.sample` file with empty variables to show what the content should be:
```
STEPZEN_ADMIN_KEY=
STEPZEN_ENDPOINT=
```

**Comment by ddebrunner** [comment]
@Cerchie thanks for the feedback.

- You should. not need to make any changes but I neglected to to add `npm install` to the instructions.
- I'm not sure about the testing in the main README, it could distract from the purpose of the repo, to provide snippets for StepZen.

**Comment by Cerchie** [comment]
> @Cerchie thanks for the feedback.
> 
> * You should. not need to make any changes but I neglected to to add `npm install` to the instructions.
> * I'm not sure about the testing in the main README, it could distract from the purpose of the repo, to provide snippets for StepZen.

Hm that's odd, because I did run npm install...
see:
```
luciacerchie@Lucias-MacBook-Pro snippets % gh pr checkout 9
Switched to branch 'initial-tests-2'
luciacerchie@Lucias-MacBook-Pro snippets % npm install

removed 8 packages, and audited 99 packages in 823ms

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
luciacerchie@Lucias-MacBook-Pro snippets % npm run test

> stepzen-snippets-test@0.0.1 test
> mocha **/tests/*Test.js

{{test list here...}}

  0 passing (9ms)
  6 failing
```
So I'm not sure what's going on.

As for the README bit -- perhaps would be good to add this information to a CONTRIBUTING.md as well rather than the top-level one.

**Comment by ddebrunner** [comment]
Hmm, works for me on a clean repo ...

**Comment by ddebrunner** [comment]
I agree on the Contributing, but think it's maybe a bit early, until we've implemented more tests and fleshed out test framework somewhat.

**Comment by ddebrunner** [comment]
Replaced by #10 - Thanks @bobbiejc

**Pull request closed without merging**
